kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-production
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: inv
        role: frontend
        env: production
    spec:
      containers:
      - name: inv-ui
        image: gcr.io/rightstuff-176212/inv-ui:master
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: []
        ports:
        - name: frontend
          containerPort: 80